Explainable boosting machine AUC

In [ ]:
pip install interpret

In [ ]:
from interpret.glassbox import ExplainableBoostingClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

dataset = pd.read_csv('/content/OS_data.csv')#//'/content/vif_x_test.csv')

# Splitting the data test into train 70% and test 30%.
# x_train, y_train are training data and labels respectively 
# x_test, y_test are testing data and labels respectively 
X_train =  dataset.iloc[:,:-1]
y_train = dataset.iloc[:,-1]

# Load imbalanced dataset
# X = np.load('data.npy')
# y = np.load('labels.npy')

# Split the dataset into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create SVM classifier with class weight parameter to handle imbalanced data
dataset_test = pd.read_csv('/content/OS_test.csv')#//'/content/vif_x_test.csv')

X_test =  dataset_test.iloc[:,:-1]
y_test = dataset_test.iloc[:,-1]

# Fit an EBM classifier
ebm = ExplainableBoostingClassifier()
ebm.fit(X_train, y_train)

# Evaluate the EBM classifier on test data
y_pred_proba = ebm.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_pred_proba)

In [ ]:
auc

0.6259784847791257

SVM AUC

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.combine import SMOTETomek
import numpy as np
import pandas as pd
# Load imbalanced dataset
dataset = pd.read_csv('/content/OS_data.csv')#//'/content/vif_x_test.csv')

# Splitting the data test into train 70% and test 30%.
# x_train, y_train are training data and labels respectively 
# x_test, y_test are testing data and labels respectively 
X_train =  dataset.iloc[:,:-1]
y_train = dataset.iloc[:,-1]

# Load imbalanced dataset
# X = np.load('data.npy')
# y = np.load('labels.npy')

# Split the dataset into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create SVM classifier with class weight parameter to handle imbalanced data
dataset_test = pd.read_csv('/content/OS_test.csv')#//'/content/vif_x_test.csv')

X_test =  dataset_test.iloc[:,:-1]
y_test = dataset_test.iloc[:,-1]

# Split the dataset into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create AdaBoost classifier with Decision Tree base estimator and class weight parameter to handle imbalanced data
base_estimator = DecisionTreeClassifier(max_depth=1, class_weight='balanced')
clf = AdaBoostClassifier(base_estimator=base_estimator)

# Define different techniques to handle imbalanced data
rus = RandomUnderSampler(random_state=42)
ros = RandomOverSampler(random_state=42)
smt = SMOTETomek(random_state=42)

# Train and test the classifier on the original imbalanced data
print('Original imbalanced data:')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test,y_pred))

# Train and test the classifier on the undersampled data
print('Random undersampling:')
X_rus, y_rus = rus.fit_resample(X_train, y_train)
clf.fit(X_rus, y_rus)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test,y_pred))
# Train and test the classifier on the oversampled data
print('Random oversampling:')
X_ros, y_ros = ros.fit_resample(X_train, y_train)
clf.fit(X_ros, y_ros)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test,y_pred))
# Train and test the classifier on the SMOTE-Tomek resampled data
print('SMOTE-Tomek resampling:')
X_smt, y_smt = smt.fit_resample(X_train, y_train)
clf.fit(X_smt, y_smt)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test,y_pred))


Original imbalanced data:


/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


              precision    recall  f1-score   support

           0       0.86      0.76      0.81       514
           1       0.15      0.26      0.19        85

    accuracy                           0.69       599
   macro avg       0.51      0.51      0.50       599
weighted avg       0.76      0.69      0.72       599

[[392 122]
 [ 63  22]]
0.5107347219043259
Random undersampling:


/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


              precision    recall  f1-score   support

           0       0.86      0.76      0.81       514
           1       0.15      0.26      0.19        85

    accuracy                           0.69       599
   macro avg       0.51      0.51      0.50       599
weighted avg       0.76      0.69      0.72       599

[[392 122]
 [ 63  22]]
0.5107347219043259
Random oversampling:


/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


              precision    recall  f1-score   support

           0       0.86      0.76      0.81       514
           1       0.15      0.26      0.19        85

    accuracy                           0.69       599
   macro avg       0.51      0.51      0.50       599
weighted avg       0.76      0.69      0.72       599

[[392 122]
 [ 63  22]]
0.5107347219043259
SMOTE-Tomek resampling:


/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


              precision    recall  f1-score   support

           0       0.86      0.76      0.81       514
           1       0.15      0.25      0.18        85

    accuracy                           0.69       599
   macro avg       0.50      0.50      0.50       599
weighted avg       0.76      0.69      0.72       599

[[391 123]
 [ 64  21]]
0.503879606317235


In [ ]:
dataset = pd.read_csv('/content/OS_data.csv')#//'/content/vif_x_test.csv')

# Splitting the data test into train 70% and test 30%.
# x_train, y_train are training data and labels respectively 
# x_test, y_test are testing data and labels respectively 
X_train =  dataset.iloc[:,:-1]
y_train = dataset.iloc[:,-1]

# Load imbalanced dataset
# X = np.load('data.npy')
# y = np.load('labels.npy')

# Split the dataset into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create SVM classifier with class weight parameter to handle imbalanced data
dataset_test = pd.read_csv('/content/OS_test.csv')#//'/content/vif_x_test.csv')

X_test =  dataset_test.iloc[:,:-1]
y_test = dataset_test.iloc[:,-1]

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm


# Train SVM classifier
clf = svm.SVC(kernel='linear') # Linear kernel
clf.fit(X_train, y_train)

# Predict test set
y_pred = clf.predict(X_test)

# Calculate accuracy
accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.6093489148580968


In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred)

0.5465323872739757